---
name: Test

on:
  - pull_request
  - push

jobs:
  preflight-job:
    name: First Step
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo "::set-output name=action_fruit::strawberry"
