---
name: Test

on:
  - pull_request
  - push

jobs:
  preflight-job:
    name: First Step
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo "::set-output name=action_fruit::strawberry"
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "test": "test message"}'
